### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by szk2s** [szk2s/spectral-mpe-editor#9]
## Feature request
- Make possible to edit Partials  interactively
    - Delete selected partial
    - Trim each partial
    - Adjust Gain
    - Interactive and Dynamic Chart with [D3.js](https://blog.logrocket.com/data-visualization-in-react-using-react-d3-c35835af16d0)  
- Drug and drop file import
- Monitor sound 
    - Simple additive synth (multiple sine wave oscillator) with Web Audio API or Tone.js
    - MIDI play-out to IAC Driver Bus  
- More neat layout with [Styled Component](https://github.com/styled-components/styled-components) and [CSS Grid](https://medium.freecodecamp.org/learn-css-grid-in-5-minutes-f582e87b1228)

**Comment by zigen** [comment]
this issue includes a lot of themes and subjects, so github project seems suitable for describing this issue and then will create issues as task for this project.
https://github.com/szk2s/spectral-mpe-editor/projects

you can also use wiki. 
https://github.com/szk2s/spectral-mpe-editor/wiki

if you want to relate issue and issue/project, project is better choice.
if you want to write roughly, wiki is better.

**Comment by szk2s** [comment]
Wow, thank you for your advice. 
I've never used project feature. I will.
